//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEğitimAkademi_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social
    {
        public int SocialId { get; set; }
        public string LinkedInUrl { get; set; }
        public string FaceBookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string GithubUrl { get; set; }
    }
}
